# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shelldatareportingapis.api_helper import APIHelper
from shelldatareportingapis.models.audit_response_audits_items import AuditResponseAuditsItems


class AuditArrayElements(object):

    """Implementation of the 'AuditArray Elements' model.

    Attributes:
        audits (List[AuditResponseAuditsItems]): The model property of type
            List[AuditResponseAuditsItems].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "audits": 'Audits'
    }

    _optionals = [
        'audits',
    ]

    def __init__(self,
                 audits=APIHelper.SKIP):
        """Constructor for the AuditArrayElements class"""

        # Initialize members of the class
        if audits is not APIHelper.SKIP:
            self.audits = audits 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        audits = None
        if dictionary.get('Audits') is not None:
            audits = [AuditResponseAuditsItems.from_dictionary(x) for x in dictionary.get('Audits')]
        else:
            audits = APIHelper.SKIP
        # Return an object of this model
        return cls(audits)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'audits={(self.audits if hasattr(self, "audits") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'audits={(self.audits if hasattr(self, "audits") else None)!s})')
