# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shelldatareportingapis.api_helper import APIHelper
from shelldatareportingapis.models.price_list import PriceList


class CustomerPriceListResponse(object):

    """Implementation of the 'CustomerPriceListResponse' model.

    Attributes:
        price_list (List[PriceList]): The model property of type
            List[PriceList].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "price_list": 'PriceList'
    }

    _optionals = [
        'price_list',
    ]

    def __init__(self,
                 price_list=APIHelper.SKIP):
        """Constructor for the CustomerPriceListResponse class"""

        # Initialize members of the class
        if price_list is not APIHelper.SKIP:
            self.price_list = price_list 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        price_list = None
        if dictionary.get('PriceList') is not None:
            price_list = [PriceList.from_dictionary(x) for x in dictionary.get('PriceList')]
        else:
            price_list = APIHelper.SKIP
        # Return an object of this model
        return cls(price_list)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'price_list={(self.price_list if hasattr(self, "price_list") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'price_list={(self.price_list if hasattr(self, "price_list") else None)!s})')
