# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PricedTransactionReqV2PeriodEnum(object):

    """Implementation of the 'PricedTransactionReqV2Period' enum.

    Pass below one of the value as per the required transaction period
    1. Last 7 Days
    2. Last 30 Days
    3. Last 90 Days

    Attributes:
        ENUM_1: TODO: type description here.
        ENUM_2: TODO: type description here.
        ENUM_3: TODO: type description here.

    """
    ENUM_1 = 1

    ENUM_2 = 2

    ENUM_3 = 3

