# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PricedTransactionReqV2SortOrderEnum(object):

    """Implementation of the 'PricedTransactionReqV2SortOrder' enum.

    Allowed Sorting Options
    1.    TransactionDateAscending
    2.    TransactionDateDescending
    3.    GrossAmountDescending
    4.    GrossAmountAscending
    5.    NetAmountAscending
    6.    NetAmountDescensding

    Attributes:
        ENUM_1: The enum member of type str.
        ENUM_2: The enum member of type str.
        ENUM_3: The enum member of type str.
        ENUM_4: The enum member of type str.
        ENUM_5: The enum member of type str.
        ENUM_6: The enum member of type str.

    """
    ENUM_1 = '1'

    ENUM_2 = '2'

    ENUM_3 = '3'

    ENUM_4 = '4'

    ENUM_5 = '5'

    ENUM_6 = '6'

