# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PricedTransactionReqV2InvoiceStatusEnum(object):

    """Implementation of the 'PricedTransactionReqV2InvoiceStatus' enum.

    Invoice status of the transactions. Mandatory Possible options:I -
    Invoiced, U – Un-Invoiced, A – All

    Attributes:
        I: TODO: type description here.
        U: TODO: type description here.
        A: TODO: type description here.

    """
    I = 'I'

    U = 'U'

    A = 'A'

