# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shelldatareportingapis.api_helper import APIHelper
from shelldatareportingapis.models.price_transaction_request import PriceTransactionRequest


class PriceTransactionReq(object):

    """Implementation of the 'PriceTransactionReq' model.

    Attributes:
        filters (PriceTransactionRequest): The model property of type
            PriceTransactionRequest.
        page (int): Page Number (as shown to the users)
        page_size (int): Page Size – Number of records to show on a page.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "filters": 'Filters',
        "page": 'Page',
        "page_size": 'PageSize'
    }

    _optionals = [
        'filters',
        'page',
        'page_size',
    ]

    _nullables = [
        'page',
        'page_size',
    ]

    def __init__(self,
                 filters=APIHelper.SKIP,
                 page=1,
                 page_size=50):
        """Constructor for the PriceTransactionReq class"""

        # Initialize members of the class
        if filters is not APIHelper.SKIP:
            self.filters = filters 
        self.page = page 
        self.page_size = page_size 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        filters = PriceTransactionRequest.from_dictionary(dictionary.get('Filters')) if 'Filters' in dictionary.keys() else APIHelper.SKIP
        page = dictionary.get("Page") if dictionary.get("Page") else 1
        page_size = dictionary.get("PageSize") if dictionary.get("PageSize") else 50
        # Return an object of this model
        return cls(filters,
                   page,
                   page_size)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'filters={(self.filters if hasattr(self, "filters") else None)!r}, '
                f'page={(self.page if hasattr(self, "page") else None)!r}, '
                f'page_size={(self.page_size if hasattr(self, "page_size") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'filters={(self.filters if hasattr(self, "filters") else None)!s}, '
                f'page={(self.page if hasattr(self, "page") else None)!s}, '
                f'page_size={(self.page_size if hasattr(self, "page_size") else None)!s})')
