# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Warning(object):

    """Implementation of the 'Warning' model.

    Attributes:
        message (str): A custom message giving the detailed outage
            information. The message will contain the duration and the reason
            for the outage.
        mtype (str): Type of warning

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message": 'Message',
        "mtype": 'Type'
    }

    def __init__(self,
                 message=None,
                 mtype=None):
        """Constructor for the Warning class"""

        # Initialize members of the class
        self.message = message 
        self.mtype = mtype 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        message = dictionary.get("Message") if dictionary.get("Message") else None
        mtype = dictionary.get("Type") if dictionary.get("Type") else None
        # Return an object of this model
        return cls(message,
                   mtype)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'message={self.message!r}, '
                f'mtype={self.mtype!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'message={self.message!s}, '
                f'mtype={self.mtype!s})')
