# -*- coding: utf-8 -*-

"""
shelldatareportingapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from shelldatareportingapis.api_helper import APIHelper
import shelldatareportingapis.exceptions.api_exception
from shelldatareportingapis.models.error_user_access_error import ErrorUserAccessError


class ErrorUserAccessError1Exception(shelldatareportingapis.exceptions.api_exception.APIException):
    def __init__(self, reason, response):
        """Constructor for the ErrorUserAccessError1Exception class

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ErrorUserAccessError1Exception, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.error = ErrorUserAccessError.from_dictionary(dictionary.get('Error')) if 'Error' in dictionary.keys() else None
